### ISSUE TITLE
Compatibility Issues after Upgrading Jersey from 3.1.9 to 3.1.10

### ISSUE THREAD

**Issue by dhanasekar416** [eclipse-ee4j/jersey#5900]
### Description
After upgrading the Jersey library from version **3.1.9** to **3.1.10**, I am encountering the following issues:

1. **Random Serialization Failure**:
   During the execution of a GET API, which returns a list of `Workspace` entities, I am encountering a **random failure** related to FasterXML Jackson serialization. The error message is as follows:

`No filter configured with id 'workspaceCurrencySetting' (type java.lang.String) (through reference chain: java.util.ArrayList[0]->com.api.rest.entity.Workspace["workspaceCurrencySetting"])`

- The `GET` API returns a list of `Workspace`, which has a field of type `WorkspaceCurrencySetting`. This field contains several `Long` and `String` properties.
- The error seems to occur **randomly** during server deployments, and not consistently.

2. **Integration Test Failure**:
- When executing integration tests, I am encountering the following exception:
`java.lang.NoClassDefFoundError for the intg class Caused by: java.lang.ExceptionInInitializerError`

### Library Version Details
- **Jersey Libraries**:
  - `org.glassfish.jersey.core` - Version: `3.1.10`
  - `org.glassfish.jersey.connectors` - Version: `3.1.10`
  - `org.glassfish.jersey.containers` - Version: `3.1.10`
  - `org.glassfish.jersey.ext` - Version: `3.1.10`
  - `org.glassfish.jersey.inject` - Version: `3.1.10`
  - `org.glassfish.jersey.media` - Version: `3.1.10`

- **FasterXML Jackson Libraries**:
  - `com.fasterxml.jackson.core` - Version: `2.18.2`
  - `jackson-databind` - Version: `2.18.2`
  - `jackson-core` - Version: `2.18.2`
  - `jackson-annotations` - Version: `2.18.2`

- **HK2 Libraries**:
  - `org.glassfish.hk2` - Version: `3.1.1`

- **Other Libraries**:
  - `org.glassfish.gmbal` - Version: `4.0.3`
  - `org.glassfish.tyrus.bundles` - Version: `2.2.0`
  - `org.glassfish.jaxb` - Version: `4.0.5`

### Additional Information
- The error related to `workspaceCurrencySetting` occurs inconsistently, making it difficult to pinpoint a specific cause.
- The `NoClassDefFoundError` and `ExceptionInInitializerError` during integration tests could be caused by missing dependencies or classpath issues introduced by the Jersey upgrade.
- The issue was not present with Jersey version `3.1.9`.

### Request for Help
I am looking for assistance to resolve the following:
1. Understanding why the serialization issue occurs randomly and how to fix it.
2. How to resolve the `NoClassDefFoundError` and `ExceptionInInitializerError` during integration tests after the upgrade.
3. Any suggestions for debugging or further investigating the cause of the issues.

**Comment by jansupol** [comment]
`NoClassDefFoundError ` sounds like a missing dependency. Running java with `-Xdiag` should tell more. 

`workspaceCurrencySetting` is not a Jersey thing. That needs to come from some other lib.

**Comment by jansupol** [comment]
Jersey 3.1.9 uses Jackson 2.17.2. Try lowering the Jackson version. Jersey should work fine with it.

**Comment by dhanasekar416** [comment]
> Jersey 3.1.9 uses Jackson 2.17.2. Try lowering the Jackson version. Jersey should work fine with it.

I have downgraded Jackson to 2.17.2 but the serialization exception for `workspaceCurrencySetting` is still being thrown randomly.
**Note** : Jackson 2.18.2 is working without any issue in Jersey 3.1.9 not sure why it is not working for 3.1.10 and even the downgraded did not work.

I am still working on debugging the `NoClassDefFoundError` with   `-Xdiag`

@jansupol Is there anything else that can be tried here to fix the issue with the library upgrade?

**Comment by jbescos** [comment]
@dhanasekar416 could you provide the full stacktrace of the errors?. Maybe we will understand better the issue that you are having.

If you provide a small reproducer it will help even more.

**Comment by dhanasekar416** [comment]
> [@dhanasekar416](https://github.com/dhanasekar416) could you provide the full stacktrace of the errors?. Maybe we will understand better the issue that you are having.
> 
> If you provide a small reproducer it will help even more.

Let me check and share you the available information.

**Comment by dhanasekar416** [comment]
After deep investigation of the regressions that appeared when upgrading from Jersey 3.1.9 to 3.1.11 (Jackson 2.18+ pulled in from Jersey 3.1.10+), we identified and fixed two distinct problems.

### 1. "No filter configured with id '…'" on nested fields / collections

**Symptoms** 

Serialization failed with exceptions such as: `No filter configured with id 'workspaceCurrencySetting'` even though both the root object and the nested object (e.g., a field in `Workspace` entity of data type `List<WorkspaceSetting>` or `WorkspaceCurrencySetting`) carried `@JsonFilter("apifilter")`.

**Root cause – Jackson 2.18+ changes**  
- Named filters are no longer automatically propagated to nested POJOs or collections of POJOs.  
- For a nested field, Jackson now requires either :
  - A named filter whose ID exactly matches the field name (impossible when the same class is reused under many different field names), or  
  - A default `PropertyFilter` set via `SerializerProvider.setDefaultFilter(...)`.  
- Additionally, filters extending `SimpleBeanPropertyFilter` are ignored when used as the default filter – only direct implementations of `PropertyFilter` are accepted.

**Fixes implemented**  
- On every serialization, explicitly call `serializerProvider.setDefaultFilter(...)` with:  
  - `SimpleBeanPropertyFilter.serializeAll()` when no projection is requested  
  - Our single refactored `ProjectionPropertyFilter` when projection is active  
- Refactored `ProjectionPropertyFilter` to implement `PropertyFilter` directly (no longer extends `SimpleBeanPropertyFilter`)
- Kept `@JsonFilter("apifilter")` on all entity classes (still required for root-level handling)

**Outcome**  

- Nested objects/collections at any depth are correctly serialized and projected and the `"No filter configured with id '...'"` exception is completely eliminated.
- Integration tests were failing because a common workspace was instantiated as a static class-level field. When the common workspace create API attempted to serialize the response, it threw the `"No filter configured with id '…'"` exception due to the filter registration issue. Once the filter registration was fixed, serialization succeeded and the integration test suite executed successfully. 

### 2. ClassCastException on Map / List / generic return types

**Symptoms**  
`ClassCastException: ParameterizedTypeImpl cannot be cast to Class` on endpoints returning `Map<…>`, `List<…>`, etc.

**Root cause**  
Two competing Jackson `MessageBodyWriter`s were registered:  
- Jersey’s bundled `org.glassfish.jersey.jackson.JacksonFeature` provider  
- Our own Jakarta EE 10-compatible custom provider  

With Jackson 2.18+ the provider selection became non-deterministic for parameterized types, sometimes picking the wrong one. Legacy providers (MOXy, old `JacksonJaxbJsonProvider`, `EntityFilteringFeature`) were also being auto-discovered.

**Primary fix**  
Removed all Jersey-bundled and legacy JSON providers. Only our explicitly registered custom `JacksonJsonProvider` remains active.

**Additional defensive configuration** (prevents future accidental registration)
```java
property(ServerProperties.FEATURE_AUTO_DISCOVERY_DISABLE, true);
property(ServerProperties.METAINF_SERVICES_LOOKUP_DISABLE, true);
property(CommonProperties.MOXY_JSON_FEATURE_DISABLE, true);
